package model;
// Generated 28-jun-2016 9:50:55 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Usuarios generated by hbm2java
 */
@Entity
@Table(name="USUARIOS"
    ,catalog="bd_objetos"
)
public class Usuarios  implements java.io.Serializable {


     private String username;
     private String pass;
     private String nombreCompleto;
     private String cedula;
     private String celular;
     private String perfil;
     private String correoElectronico;
     private Date fechaRegistro;
     private String imagenPerfil;
     private Set reportes = new HashSet(0);

    public Usuarios() {
    }

	
    public Usuarios(String username) {
        this.username = username;
    }
    public Usuarios(String username, String pass, String nombreCompleto, String cedula, String celular, String perfil, String correoElectronico, Date fechaRegistro, String imagenPerfil, Set reportes) {
       this.username = username;
       this.pass = pass;
       this.nombreCompleto = nombreCompleto;
       this.cedula = cedula;
       this.celular = celular;
       this.perfil = perfil;
       this.correoElectronico = correoElectronico;
       this.fechaRegistro = fechaRegistro;
       this.imagenPerfil = imagenPerfil;
       this.reportes = reportes;
    }
   
     @Id 

    
    @Column(name="USERNAME", unique=true, nullable=false, length=50)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="PASS", length=50)
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }

    
    @Column(name="NOMBRE_COMPLETO", length=50)
    public String getNombreCompleto() {
        return this.nombreCompleto;
    }
    
    public void setNombreCompleto(String nombreCompleto) {
        this.nombreCompleto = nombreCompleto;
    }

    
    @Column(name="CEDULA", length=20)
    public String getCedula() {
        return this.cedula;
    }
    
    public void setCedula(String cedula) {
        this.cedula = cedula;
    }

    
    @Column(name="CELULAR", length=20)
    public String getCelular() {
        return this.celular;
    }
    
    public void setCelular(String celular) {
        this.celular = celular;
    }

    
    @Column(name="PERFIL", length=5)
    public String getPerfil() {
        return this.perfil;
    }
    
    public void setPerfil(String perfil) {
        this.perfil = perfil;
    }

    
    @Column(name="CORREO_ELECTRONICO", length=30)
    public String getCorreoElectronico() {
        return this.correoElectronico;
    }
    
    public void setCorreoElectronico(String correoElectronico) {
        this.correoElectronico = correoElectronico;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FECHA_REGISTRO", length=19)
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }

    
    @Column(name="IMAGEN_PERFIL", length=200)
    public String getImagenPerfil() {
        return this.imagenPerfil;
    }
    
    public void setImagenPerfil(String imagenPerfil) {
        this.imagenPerfil = imagenPerfil;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usuarios")
    public Set getReportes() {
        return this.reportes;
    }
    
    public void setReportes(Set reportes) {
        this.reportes = reportes;
    }




}


